# Generated by Django 2.2.5 on 2019-10-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191007_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profile_image',
            field=models.URLField(max_length=1000),
        ),
    ]
